export const accountData = [
  { acct_num: "US-AK", acct_type: "jcb", acct_nam: "dskillicorn0" },
  { acct_num: "TD-SA", acct_type: "jcb", acct_nam: "fbraysher1" },
  { acct_num: "CD-BN", acct_type: "jcb", acct_nam: "ljanz2" },
  { acct_num: "MM-06", acct_type: "switch", acct_nam: "gkener3" },
  { acct_num: "AU-WA", acct_type: "jcb", acct_nam: "mhachette4" },
  { acct_num: "UY-CL", acct_type: "bankcard", acct_nam: "mgergher5" },
  { acct_num: "AU-QLD", acct_type: "laser", acct_nam: "mpfertner6" },
  { acct_num: "SE-AC", acct_type: "bankcard", acct_nam: "emcgaw7" },
  {
    acct_num: "AU-TAS",
    acct_type: "diners-club-enroute",
    acct_nam: "jgladdolph8",
  },
  {
    acct_num: "DZ-05",
    acct_type: "diners-club-carte-blanche",
    acct_nam: "hmcgrail9",
  },
  { acct_num: "US-TX", acct_type: "jcb", acct_nam: "npimma" },
  { acct_num: "RU-YAR", acct_type: "jcb", acct_nam: "rsoaresb" },
  { acct_num: "AU-SA", acct_type: "maestro", acct_nam: "ndorroc" },
  { acct_num: "US-MS", acct_type: "china-unionpay", acct_nam: "hkupiszd" },
  { acct_num: "FR-M", acct_type: "jcb", acct_nam: "lsantone" },
  { acct_num: "US-MO", acct_type: "bankcard", acct_nam: "plivingstonf" },
  { acct_num: "PG-CPM", acct_type: "jcb", acct_nam: "pklewerg" },
  { acct_num: "MW-SA", acct_type: "jcb", acct_nam: "wkleinlererh" },
  { acct_num: "US-NJ", acct_type: "jcb", acct_nam: "dbicklei" },
  { acct_num: "BR-SP", acct_type: "jcb", acct_nam: "oburnyeatj" },
  {
    acct_num: "PG-WBK",
    acct_type: "diners-club-enroute",
    acct_nam: "tklugerk",
  },
  { acct_num: "FR-D", acct_type: "visa-electron", acct_nam: "dmasseol" },
  { acct_num: "AO-MAL", acct_type: "jcb", acct_nam: "cgaskinm" },
  { acct_num: "AR-Z", acct_type: "jcb", acct_nam: "shuguesn" },
  { acct_num: "US-AK", acct_type: "jcb", acct_nam: "swoolstenholmeso" },
  {
    acct_num: "GF-SL",
    acct_type: "diners-club-carte-blanche",
    acct_nam: "dloughtonp",
  },
  { acct_num: "PG-NPP", acct_type: "jcb", acct_nam: "kmcgeaneyq" },
  { acct_num: "US-WY", acct_type: "switch", acct_nam: "bgudemanr" },
  { acct_num: "GG-U-A", acct_type: "jcb", acct_nam: "rbyllams" },
  { acct_num: "RU-KYA", acct_type: "jcb", acct_nam: "kjoront" },
  {
    acct_num: "AU-WA",
    acct_type: "diners-club-carte-blanche",
    acct_nam: "langoodu",
  },
  { acct_num: "AU-NT", acct_type: "maestro", acct_nam: "kdmitrievv" },
  { acct_num: "MY-07", acct_type: "americanexpress", acct_nam: "ffewtrellw" },
  { acct_num: "JP-22", acct_type: "americanexpress", acct_nam: "rfiridolfix" },
  { acct_num: "US-FL", acct_type: "china-unionpay", acct_nam: "cwaplintony" },
  { acct_num: "AU-WA", acct_type: "china-unionpay", acct_nam: "epotesz" },
  { acct_num: "VE-P", acct_type: "china-unionpay", acct_nam: "sconws10" },
  { acct_num: "MY-13", acct_type: "jcb", acct_nam: "parendsen11" },
  { acct_num: "ET-BE", acct_type: "diners-club-enroute", acct_nam: "mjenks12" },
  { acct_num: "NO-08", acct_type: "bankcard", acct_nam: "nlubbock13" },
  { acct_num: "TH-64", acct_type: "americanexpress", acct_nam: "hbillings14" },
  { acct_num: "KI-L", acct_type: "jcb", acct_nam: "bheadey15" },
  { acct_num: "CO-ANT", acct_type: "jcb", acct_nam: "cstitcher16" },
  { acct_num: "MG-M", acct_type: "jcb", acct_nam: "llochet17" },
  { acct_num: "US-OR", acct_type: "jcb", acct_nam: "cscarrott18" },
  { acct_num: "SB-WE", acct_type: "jcb", acct_nam: "bbluett19" },
  { acct_num: "BS-NB", acct_type: "jcb", acct_nam: "fharmes1a" },
  { acct_num: "UG-406", acct_type: "china-unionpay", acct_nam: "bmatyugin1b" },
  {
    acct_num: "US-OK",
    acct_type: "americanexpress",
    acct_nam: "cstewartson1c",
  },
  { acct_num: "CI-17", acct_type: "jcb", acct_nam: "llovekin1d" },
  { acct_num: "BR-BA", acct_type: "jcb", acct_nam: "jstollenwerck1e" },
  { acct_num: "MX-TAM", acct_type: "visa", acct_nam: "sdwerryhouse1f" },
  { acct_num: "AU-QLD", acct_type: "switch", acct_nam: "hlosel1g" },
  { acct_num: "US-IL", acct_type: "visa", acct_nam: "mriccardi1h" },
  { acct_num: "ET-SO", acct_type: "visa-electron", acct_nam: "jkeoghan1i" },
  { acct_num: "US-CA", acct_type: "bankcard", acct_nam: "vsposito1j" },
  { acct_num: "BR-AM", acct_type: "jcb", acct_nam: "rblaymires1k" },
  { acct_num: "PG-EHG", acct_type: "jcb", acct_nam: "sardy1l" },
  { acct_num: "US-WA", acct_type: "visa-electron", acct_nam: "mgrundell1m" },
  { acct_num: "US-CA", acct_type: "jcb", acct_nam: "ogronw1n" },
  { acct_num: "CY-02", acct_type: "switch", acct_nam: "jfrew1o" },
  { acct_num: "PG-MPM", acct_type: "laser", acct_nam: "tlosano1p" },
  {
    acct_num: "CA-ON",
    acct_type: "diners-club-carte-blanche",
    acct_nam: "fbedson1q",
  },
  { acct_num: "NE-1", acct_type: "mastercard", acct_nam: "bfeechum1r" },
  { acct_num: "CA-ON", acct_type: "switch", acct_nam: "gveysey1s" },
  { acct_num: "US-CA", acct_type: "visa", acct_nam: "oforsdike1t" },
  { acct_num: "PY-1", acct_type: "bankcard", acct_nam: "depdell1u" },
  { acct_num: "CA-QC", acct_type: "china-unionpay", acct_nam: "arichmont1v" },
  { acct_num: "RU-AMU", acct_type: "switch", acct_nam: "phuggett1w" },
  { acct_num: "AU-QLD", acct_type: "jcb", acct_nam: "jdriscoll1x" },
  { acct_num: "CR-P", acct_type: "visa", acct_nam: "mkerslake1y" },
  { acct_num: "AU-NT", acct_type: "maestro", acct_nam: "stwidle1z" },
  { acct_num: "ZA-NP", acct_type: "visa-electron", acct_nam: "aaltimas20" },
  { acct_num: "ID-JB", acct_type: "switch", acct_nam: "wedmund21" },
  { acct_num: "PH-MDC", acct_type: "mastercard", acct_nam: "bscreeton22" },
  { acct_num: "CN-15", acct_type: "jcb", acct_nam: "fklimowicz23" },
  { acct_num: "IN-BR", acct_type: "mastercard", acct_nam: "ameekin24" },
  { acct_num: "CA-BC", acct_type: "bankcard", acct_nam: "asarton25" },
  { acct_num: "CA-NT", acct_type: "visa-electron", acct_nam: "loscroft26" },
  { acct_num: "EG-JS", acct_type: "jcb", acct_nam: "spetyankin27" },
  { acct_num: "GT-AV", acct_type: "jcb", acct_nam: "mtodor28" },
  { acct_num: "RU-SAK", acct_type: "jcb", acct_nam: "wgunston29" },
  { acct_num: "NA-KE", acct_type: "jcb", acct_nam: "lconlaund2a" },
  { acct_num: "CL-VS", acct_type: "switch", acct_nam: "yseamans2b" },
  { acct_num: "US-MT", acct_type: "jcb", acct_nam: "astewart2c" },
  { acct_num: "SB-ML", acct_type: "visa-electron", acct_nam: "bmcnulty2d" },
  { acct_num: "BR-PA", acct_type: "maestro", acct_nam: "mlogie2e" },
  { acct_num: "GB-ENG", acct_type: "jcb", acct_nam: "geller2f" },
  { acct_num: "BR-RS", acct_type: "visa-electron", acct_nam: "ewhitnall2g" },
  { acct_num: "US-IN", acct_type: "china-unionpay", acct_nam: "kpalfreman2h" },
  { acct_num: "MZ-T", acct_type: "jcb", acct_nam: "jloveguard2i" },
  { acct_num: "KM-G", acct_type: "mastercard", acct_nam: "nbadrick2j" },
  { acct_num: "US-CO", acct_type: "mastercard", acct_nam: "athridgould2k" },
  { acct_num: "JP-42", acct_type: "instapayment", acct_nam: "nlamblin2l" },
  { acct_num: "DZ-03", acct_type: "maestro", acct_nam: "rinstone2m" },
  { acct_num: "PW-004", acct_type: "jcb", acct_nam: "bflagg2n" },
  { acct_num: "US-FL", acct_type: "maestro", acct_nam: "gfaier2o" },
  { acct_num: "CN-31", acct_type: "mastercard", acct_nam: "lserver2p" },
  { acct_num: "ID-PA", acct_type: "jcb", acct_nam: "bcutford2q" },
  { acct_num: "JP-32", acct_type: "jcb", acct_nam: "gbowfin2r" },
];

export type Account = (typeof accountData)[number];
